name: GitHub 3D Contribution Calendar

on:
  schedule:
    # Runs at 18:00 UTC every day
    - cron: '0 18 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Grid
    steps:
      - uses: actions/checkout@v4
      
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: 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
          USERNAME: ${{ github.repository_owner }}
          
      - name: Commit & Push generated assets
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A profile-3d-contrib
          git commit -m "Update 3D contribution graph [skip ci]" || exit 0
          git push